processManagement:
  fork: true

storage:
  dbPath: ../data/--NODE--
  journal:
    enabled: true
  engine: wiredTiger
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.5

systemLog:
  destination: file
  path: ../data/--NODE--.log
  verbosity: 1

net:
  port: --PORT--
  bindIp: 127.0.2.1,192.168.0.42
  unixDomainSocket:
    enabled: false
  ssl:
    mode: preferSSL
    PEMKeyFile: tls-certs/public-server-key-cert.pem
    CAFile: tls-certs/public-signing-ca-root.pem
    allowConnectionsWithoutCertificates: true

security:
  authorization: enabled
# keyFile: keyfiles/keyfile-atrest.txt
  clusterAuthMode: x509

setParameter:
  authenticationMechanisms: SCRAM-SHA-1,SCRAM-SHA-256,MONGODB-X509

replication:
  replSetName: --CONFIG--
