processManagement:
  fork: true

storage:
  dbPath: data/--NODE--
  journal:
    enabled: true
  engine: wiredTiger
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.5

systemLog:
  destination: file
  path: data/--NODE--.log
  verbosity: 1

net:
  port: --PORT--
  bindIp: 0.0.0.0
  unixDomainSocket:
    enabled: false
  tls:
    mode: preferTLS
    CertificateKeyFile: tls/private/server-key-cert.pem
    CAFile: tls/ca-chain.pem
    allowConnectionsWithoutCertificates: true

security:
  authorization: enabled
#  keyFile: tls/private/keyfile.key
  clusterAuthMode: x509

setParameter:
  authenticationMechanisms: SCRAM-SHA-1,SCRAM-SHA-256,MONGODB-X509

replication:
  replSetName: --CONFIG--
