processManagement:
  fork: true

storage:
  dbPath: ../data/--NODE--
  journal:
    enabled: true
  engine: wiredTiger
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1

systemLog:
  destination: file
  path: ../data/--NODE--.log
  verbosity: 1

#operationProfiling:
#  slowOpThresholdMs: 0

net:
  port: --PORT--
  bindIp: 127.0.2.1
  unixDomainSocket:
    enabled: false
  ssl:
#    mode: allowSSL../
    mode: preferSSL
#    mode: requireSSL
    PEMKeyFile: tls-certs/public-server-key-cert.pem
    CAFile: tls-certs/public-ca.pem
#    clusterFile: tls-certs/internal-server-key-cert.pem
#    clusterCAFile: tls-certs/internal-ca.pem
    allowConnectionsWithoutCertificates: true

security:
  authorization: enabled
# keyFile: keyfiles/keyfile-atrest.txt
  clusterAuthMode: x509

setParameter:
#  initialSyncOplogBufferPeekCacheSize: 1000
#  authenticationMechanisms: PLAIN
#  authenticationMechanisms: SCRAM-SHA-1,MONGODB-X509,SCRAM-SHA-256
  authenticationMechanisms: SCRAM-SHA-1,MONGODB-X509

replication:
  replSetName: --CONFIG--
#  enableMajorityReadConcern: false
