# config for config server

processManagement:
  fork: true

storage:
  dbPath: ../data/config
  journal:
    enabled: true
  engine: wiredTiger
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.5

systemLog:
  destination: file
  path: ../data/config.log
  verbosity: 0

auditLog:
  destination: file
  format: JSON
  path: ../data/audit-config.log
  filter: '{ atype: { $in: [ "createCollection", "dropCollection" ] } }'

net:
  bindIp: 0.0.0.0
  port: 27016
  unixDomainSocket:
    enabled: false
  ssl:
    mode: preferSSL
    PEMKeyFile: tls-certs/public-server-key-cert.pem
    CAFile: tls-certs/public-signing-ca-root.pem
    disabledProtocols: "TLS1_0,TLS1_1"
    allowConnectionsWithoutCertificates: true

security:
  authorization: enabled
  clusterAuthMode: x509
#  keyFile: tls-certs/server.keyfile

setParameter:
    authenticationMechanisms: SCRAM-SHA-1,SCRAM-SHA-256,MONGODB-X509

replication:
  replSetName: cs

sharding:
  clusterRole: configsvr
